#!/bin/sh
set -e
case "$1" in
    configure)
    ln -s -f /usr/share/eos-social /usr/lib/python2.7/dist-packages/
    mkdir -p /home/endlessm/.endlessm/social_bar/images/
    chmod -R 777 /home/endlessm/.endlessm/social_bar/images/
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    rm -f /usr/lib/python2.7/dist-packages/eos-social
    rm -f /home/endlessm/.endlessm/social_bar/images
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0
